# automation/awning_automation.yaml

- alias: Tenda Apertura Mattina
  description: ""
  trigger:
    - platform: sun
      event: sunrise
      offset: "+02:00"
  condition:
    - condition: template
      value_template: "{{ now().month in [5,6,7,8,9,10] and now().weekday() in [5,6] }}"
    - condition: numeric_state
      entity_id: weather.forecast_home
      below: 10
      attribute: wind_speed
    - condition: numeric_state
      entity_id: weather.forecast_home
      below: 44
      attribute: cloud_coverage
    - condition: numeric_state
      entity_id: zone.home
      above: 1
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.tenda_solare
    - service: notify.notify
      data:
        message: "La tenda è stata aperta automaticamente in quanto risultano persone presenti in casa e le condizioni meteo sono favorevoli."
        title: "TENDA APERTA"